name: Webdriver tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install XVFB
        run: sudo apt-get install xvfb

      - name: Adding Google Chrome signing key
        run: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add 

      - name: Adding Google Chrome reporitory
        run: echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list 

      - name: Updating package list 
        run: sudo apt-get update 

      - name: Installing Google Chrome 
        run: sudo apt-get install google-chrome-stable 

      - name: Start tests on xvfb screen
        run: xvfb-run -a --server-args="-screen 0 1920x1080x24 -ac -nolisten tcp -dpi 96 +extension RANDR" mvn --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn --update-snapshots test
        env:
          TEST: bot

      - name: Upload Screenshots
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: target/screenshots/

      - name: Upload Runs
        uses: actions/upload-artifact@v2
        with:
          name: runs
          path: target/runs/

      - name: Surefire reports
        uses: actions/upload-artifact@v2
        with:
          name: surefire-reports
          path: target/surefire-reports/

      - name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        continue-on-error: true
        
